yaml
name: Aggiungi Film alla Lista

on:
  workflow_dispatch:
    inputs:
      id_film:
        description: 'ID Film'
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
    contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Aggiorna lista
        run: |
          touch lista.txt
          echo "https://vixsrc.to{{ github.event.inputs.id_film }}?lang=it" >> lista.txt
          sort -u lista.txt -o lista.txt

          - name: Salva modifiche
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add lista.txt
          git commit -m "Aggiunto film ${{ github.event.inputs.id_film }}" || exit 0
          git push
    
        
